"FINAL RESULTS!!!\n"
"\n"
"PC DEMO\n"
"\n"
"    1    10 (3646 points)     Nooon \"Stars : Wonders of the world\"\n"
"    2     7 (1482 points)     Psychic Link \"Juice\"\n"
"    3    12 (1204 points)     RealTech \"DX Project\"\n"
"    4     1 (1039 points)     Capacala \"Zweilight Zone\"\n"
"    5     2 (916 points)      Epical \"Rebel Mind\"\n"
"    6     3 (896 points)      Miracle \"Higher Desire\"\n"
"    7    15 (799 points)      Orange \"Television\"\n"
"    8     5 (587 points)      Dubius \"Optimal Torque\"\n"
"    9     8 (541 points)      Kosmic \"Little Green Men\"\n"
"   10    13 (372 points)      Japotek \"Fighting for something\"\n"
"   11     4 (224 points)      Masque \"Mystery\"\n"
"   12     6 (175 points)      tArzAn tuotanto \"Syllabization\"\n"
"   13    11 (153 points)      Black Rain \"Overflow\"\n"
"   14     9 (143 points)      Deus ex Machina \"Fever\"\n"
"   15    14 (33 points)       Simplicity \"Elegant\"\n"
"                              A-Men \"Dino\"\n"
"                              Amorphous \"Phlox\"\n"
"                              Artos \"Syndrome-X\"\n"
"                              Asathor \"Black Dawn\"\n"
"                              COMA \"John Lennon Isn't Dead\"\n"
"                              CWU \"Firemania\"\n"
"                              DCC \"Shock\"\n"
"                              DDG \"Beta\"\n"
"                              Flexion \"Inflexion\"\n"
"                              Fobia Design \"Attack\"\n"
"                              Jolly Workers \"Opera\"\n"
"                              Oklahoma \"Jeriko\"\n"
"                              Plant \"Divine Booty\"\n"
"                              Radon \"Distance\"\n"
"                              The Underworld Corporation \"Dea Parca\"\n"
"                              Trillian \"Triangle\"\n"
"                              Vettje \"Aiku - the Beginning\"\n"
"\n"
"AMIGA DEMO\n"
"\n"
"    1    11 (2917 points)     Parallax \"ZIF\"\n"
"    2     9 (1950 points)     Pygmy Projects \"Logic\"\n"
"    3    12 (1366 points)     Stellar \"Miracles\"\n"
"    4    10 (1224 points)     Silents \"Fruit Kitchen\"\n"
"    5     2 (980 points)      Juliet and Case \"C42\"\n"
"    6     7 (902 points)      Complex \"Dive\"\n"
"    7     8 (457 points)      Fanatic \"Hate 2\"\n"
"    8     6 (356 points)      Balance \"Embryo\"\n"
"    9     4 (317 points)      Zymosis \"Wc goes to wc\"\n"
"   10     3 (281 points)      Embassy \"Thrilled\"\n"
"   11     1 (235 points)      Abyss \"High Anxiety\"\n"
"   12    13 (217 points)      The Black Lotus \"Misery\"\n"
"   13     5 (115 points)      Domination \"Domination's Dentro\"\n"
"\n"
"PC 64K INTRO\n"
"\n"
"    1     4 (2750 points)     Wild Light \"Drift\"\n"
"    2    10 (1899 points)     Coma \"Stickman's World\"\n"
"    3    15 (1364 points)     Complex \"Bill G Force\"\n"
"    4    14 (1219 points)     Jamm \"Nation Zero\"\n"
"    5     2 (1112 points)     Halcyon \"Detour\"\n"
"    6    13 (1041 points)     Valhalla \"Believe\"\n"
"    7     1 (527 points)      Mist \"Alchymia\"\n"
"    8     6 (506 points)      Halo \"Reality Impact\"\n"
"    9     3 (471 points)      Symptom \"Camera\"\n"
"   10    11 (364 points)      Abaddon \"Pied\"\n"
"   11     9 (358 points)      Epsilon \"Dream\"\n"
"   12     7 (271 points)      Hazard \"Cocaholic\"\n"
"   13    12 (225 points)      Anarchy \"Tam\"\n"
"   14     8 (194 points)      Woodpeckers from Mars \"No Class\"\n"
"   15     5 (185 points)      @ \"Byte me\"\n"
"                              Onyx \"2nd\"\n"
"                              The Zealots \"Motion\"\n"
"                              The Dynamic Force \"The Last Dimension\"\n"
"                              Disease \"Ugly\"\n"
"                              Velocity \"Dong\"\n"
"                              Epigon \"Democrators\"\n"
"                              Tunnelbana \"Tunnelbana\"\n"
"                              Mewlers \"Go\"\n"
"                              Deck Blasters \"Seasons\"\n"
"                              Deus \"Fruitcake\"\n"
"                              Le Fongus Jaune \"Net\"\n"
"                              Fit \"SUGA\"\n"
"                              Fit \"Mansikka\"\n"

