"/*\n"
" * Run by the OPen command in main menu. Remember to recompile!\n"
" */\n"
"\n"
"function logdoor($door) {\n"
"  if (fopen(0,$bl_logfile,\"at\")) {\n"
"    fprintf(0,\"%02u:%02u Opened door %u\\n\",$bf_hour,$bf_min,$door);\n"
"    fclose(0);\n"
"  }\n"
"}\n"
"\n"
"function make_dorinfo1def($fn) {\n"
"  var $foo, $nam1, $nam2, $sys1, $sys2, $security;\n"
"\n"
"  if (!fopen(0,$fn,\"wt\")) {\n"
"    printf(\"No way, %s, man!\",$fn);\n"
"    return(1);\n"
"  }\n"
"  if ($bv_unum==0) $security=32000;\n"
"  else $security=1;\n"
"  $nam1=copy($bu_name,1,pos(\" \",$bu_name)-1);\n"
"  $nam2=copy($bu_name,pos(\" \",$bu_name)+1,30);\n"
"  $sys1=copy($bg_sysop_name,1,pos(\" \",$bg_sysop_name)-1);\n"
"  $sys2=copy($bg_sysop_name,pos(\" \",$bg_sysop_name)+1,30);\n"
"  if (!$bv_com) $foo=0;\n"
"  else $foo=$bv_baud;\n"
"//             1   2   3      4   5              6  7   8   9  10  11  12\n"
"  fprintf(0,\"%s\\n%s\\n%s\\nCOM%u\\n%u BAUD,N,8,1\\n%u\\n%s\\n%s\\n%s\\n%u\\n%u\\n%d\\n\",\n"
"      $bg_sysop_name,                 // 1    - BBS name\n"
"      $sys1,                          // 2    - SysOp first name\n"
"      $sys2,                          // 3    - SysOp last name\n"
"      $bv_com,                        // 4    - COM port\n"
"      $foo,                           // 5    - Baud rate\n"
"      $foo,                           // 6    - Baud, again\n"
"      $nam1,                          // 7    - User first name\n"
"      $nam2,                          // 8    - User last name\n"
"      $bu_city,                       // 9    - User location\n"
"      ($bu_termcap & 15)>0,           // 10   - ANSI (1/0)\n"
"      $security,                      // 11   - user security\n"
"      $bf_timleft);                   // 12   - Time left\n"
"  fclose(0);\n"
"  return(0);\n"
"}\n"
"\n"
"function make_doorsys($fn) {\n"
"  var $foo;\n"
"\n"
"  if (fopen(0,$fn,\"wt\")) {\n"
"    fprintf(0,\"%s\\n%u\\n%u\\n%d\\nG\\nA\\n\",$bu_name,$bv_com,\n"
"      $bv_realbaud,$bf_timleft);\n"
"    fclose(0);\n"
"  }\n"
"}\n"
"\n"
"function main() {\n"
"  var $b, $z, $n;\n"
"\n"
"  if (($n=$bn_zstatus)==1) $bn_zstatus=8;\n"
"  if ($bv_comstring==\"\") showfile(strcat($bg_menudir,\"doormenu\"));\n"
"  do {\n"
"    switch ($z=parsecom(\"Quit/?/1/2/3/4/5\",$b=input(\"Number of door to open: \",60,1))) {\n"
"       case 2:{\n"
"                showfile(strcat($bg_menudir,\"doormenu\"));\n"
"                break;\n"
"              }\n"
"       case 3:{\n"
"                if (yellsysop(0)) {\n"
"                  logdoor(1);\n"
"                  tictactoe(1,0);\n"
"                }\n"
"                break;\n"
"              }\n"
"       case 4:{\n"
"                if (yellsysop(0)) {\n"
"                  tictactoe(2,1);\n"
"                  logdoor(2);\n"
"                }\n"
"                break;\n"
"              }\n"
"       case 5:{\n"
"                if (yellsysop(0)) {\n"
"                  tictactoe(2,2);\n"
"                  logdoor(3);\n"
"                }\n"
"                break;\n"
"              }\n"
"       case 6:{\n"
"                if (yellsysop(0)) {\n"
"                  logdoor(4);\n"
"                  make_dorinfo1def(sprintf(\"dorinfo%u.def\",$bv_nodenumber));\n"
"                  make_doorsys(sprintf(\"door%u.sys\",$bv_nodenumber));\n"
"                  make_pcboard12sys(sprintf(\"pcb%u.s12\",$bv_nodenumber));\n"
"                  make_pcboard14sys(sprintf(\"pcb%u.s14\",$bv_nodenumber));\n"
"                  system(\"lw2 s3 duel\",1);\n"
"                }\n"
"                break;\n"
"              }\n"
"       case 7:{\n"
"                logdoor(5);\n"
"                spawn(\"mastermind\");\n"
"                break;\n"
"              }\n"
"     case 255:{\n"
"                printf(\"%s\\\"%s\\\".\\n\",$bv_txt[23],$b);\n"
"                $bv_comstring=\"\";\n"
"                break;\n"
"              }\n"
"    }\n"
"  } while ($bv_carrier && ($z==2 || $z==255));\n"
"  $bn_zstatus=$n;\n"
"}\n"
"\n"

