"(H)eLP, (1-37), FiLE LiST k\x8fMMaNd?? u\n"
"J-PALMU.ZIP      3147  06.10.94* Jukka Palmu (Alias=ABSURD)\n"
"                                 kuoli my\x94h\x84\x84n torstai-\n"
"                                 iltana 15.09.1994,\n"
"                                 auto-onnettomuudessa.\n"
"                                 Antaa Jukan lev\x84t\x84 rauhassa.\n"
"                                 Vain laamat nauravat h\x84nen\n"
"                                 kuolemalleen. Nuoren kuolema\n"
"                                 on AINA hiljentymisen\n"
"                                 arvoista, oli se sitten\n"
"                                 laama tai ei!\n"
"                                 (EI FAKEJUTTU!)\n"
"                                 Uploaded by: sUpERKiLLER\n"
"SFSCENE.ZIP      6725  08.10.94* .------------------------------------.\n"
"                                 | * FINNISH PIRATE-SCENE MANIFESTO * |\n"
"                                 | mihin suomalainen piraattiskene on |\n"
"                                 | oikein menossa? mielipiteit\x84 esim. |\n"
"                                 | -wannabe elite piraattikannuista   |\n"
"                                 | -wannabe elite luuseripelleist\x84    |\n"
"                                 | -xxxxxxx is lame fileist\x84          |\n"
"                                 | ALMOST FREE TO DL * ODOTAN REPLYJ\x8e |\n"
"                                 `------------------------------------'\n"
"                                 Uploaded by: sUpERKiLLER\n"
"<t\x84h\x84n moretus>\n"
"CWU-MK2.ZIP      4148  09.10.94* \xda\xc4\xbf\xfe C00LeS WaReZ UNiON PRoUDLY PReSENTS \xfe\xda\xc4\xbf\n"
"                                 \xb3 .                                       . \xb3\n"
"                                 \xb3    MIKKO KALLIO IS MUCH LAMER OSA 2!!!    \xb3\n"
"                                 \xb3    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    \xb3\n"
"                                 \xb3                                           \xb3\n"
"                                 \xb3  JA MIKKO \"MOOTTORISAHAPORNO\" KALLION     \xb3\n"
"                                 \xb3  (12 VUOTTA) KUSETUS JATKUU J\x8eLLEEN!!!    \xb3\n"
"                                 \xb3                                           \xb3\n"
"                                 \xb3    LUE JA KUOLE NAURUUN, PAKKOIMU!!!      \xb3\n"
"                                 \xb3                                           \xb3\n"
"                                 \xb3    CaPtUReD bY oUR ReTuRNeD MEmBERz:      \xb3\n"
"                                 \xb3    dA dArK ELiTE & MoTHeR FuCKeR !!!      \xb3\n"
"                                 \xb3 .                                       . \xb3\n"
"                                 \xc0\xc4\xc4\xc4\xc4\xc4\xc4\xc4\xc4\xc4\xc4\xc4\xc4\xc4\xc4\xc4\xc4[DiZzEd bY FaTHeR FuCKeR]\xc4\xc4\xd9\n"
"                                 Uploaded by: mR.mEgAsTuFf\n"
"(H)eLP, (1-37), FiLE LiST k\x8fMMaNd??\n"

