"           - * - GateNet rules 1.6.1995 - * -\n"
"\n"
"NOTE: CONSIDERABLE CHANGES IN THE RULES ON 1.6.1995!\n"
"FAMILIARIZE YOURSELF WITH THE NEW RULES AND KNOW YOUR RESPONSIBILITIES!\n"
"\n"
"\x15 1. All GateNet systems must USE THE LATEST NODELIST. The new nodelist must\n"
"be taken in use within three (3) days of its release, or THE SYSTEM WILL\n"
"BE REMOVED FROM THE NETWORK!!! In addition, it should be obvious to everyone\n"
"that FORGING the Nodelist is ABSOLUTELY IMMORAL and the one who does it\n"
"will get A PERMANENT BAN to GateNet and will also have business WITH THE\n"
"AUTHORITIES!\n"
"\n"
"\x15 2. GateNet uses the IBM character set. If your system uses another\n"
"character set, the mailer must be configured to convert all the outward\n"
"messages into the IBM character set. GateNet is ONLY FOR THOSE whose\n"
"CHARACTERS WORK!!! 7-bit scandies are considered non-working.\n"
"\n"
"\x15 3. The messages must be written TO THE AREAS THAT MATCH THEIR TOPICS!\n"
"The names and descriptions of the areas are in the file GNAREAS.TXT.\n"
"\n"
"\x15 4. The SUBJECT LINES of the messages must match the topics! If the topic\n"
"of the reply no longer matches the original message, THE SUBJECT LINE MUST\n"
"BE CHANGED to a better descriptive one!\n"
"\n"
"\x15 5. Messages should be written in a careful and correct language!\n"
"Swearwords are forbidden, as are deliberate errors (which include the use of\n"
"spoken language or leaving out the capital letters).\n"
"\n"
"\x15 6. The ones who use the childish \"eLiTE\" writing (even in just the\n"
"signature) WILL GET THEIR WRITING ACCESS REMOVED WITHOUT WARNING!!!\n"
"\n"
"\x15 7. The ones who constantly make elementary school level mistakes in\n"
"grammar, spelling etc. will be recommended to stop writing messages until\n"
"the comprehensive school curriculum is adequately completed.\n"
"\n"
"\x15 8. The messages must STAY IN TOPIC! In debate, one MUST NOT START\n"
"INSULTING the opponent but only concentrate on the issue! VANITY CHIT-CHAT\n"
"(such as sharing everyday news) MUST NOT BE PRACTICED!! No one is interested\n"
"that you got fired from your job or what you ate for dinner.\n"
"\n"
"\x15 9. The accepted quoting styles are:\n"
"\n"
"  XX> - i.e. the writer's initials followed by angle bracket\n"
"  >   - i.e. just the angle bracket\n"
"  So, especially PCBoard's stupid \"->\" is forbidden!\n"
"\n"
"  There must ALWAYS be one (1) empty line between quote and own text!\n"
"\n"
"  IT IS ABSOLUTELY FORBIDDEN TO REPLY WITHOUT A QUOTE OR ABOVE THE QUOTE AND\n"
"  ALL THAT KIND OF NON-STANDARD STUFF!!!\n"
"\n"
"\x15 10. The proper amount of quote is 50%-200% of the amount of text written\n"
"under it (in lines). If the amount of quote considerably differs from this\n"
"norm, the writer will be given a warning, and on the second time THE\n"
"WRITING ACCESS WILL BE GONE!!!\n"
"\n"
"\x15 11. GateNet uses REAL NAMES, i.e. not made-up names and especially not\n"
"any stupid handles. The SysOp of a GateNet system must check the names of\n"
"every user before granting them writing access to GateNet.\n"
"\n"
"\x15 12. It is recommended that the SysOp will install the official GateNet\n"
"maturity test (GNTEST.ZIP) and does not let anyone write in GateNet unless\n"
"the test is succesfully completed. Amiga version of the test coming soon!\n"
"\n"
"\x15 13. ONLY THE MODERATOR has the right to give notifications for rule\n"
"violations! The moderator of each area is given in GNAREAS.TXT. If the\n"
"assigned moderator of an area does not notice the violation, then the other\n"
"moderators can also take action.\n"
"\n"
"\x15 14. If the SysOp neglects the responsibilities of removing the writing\n"
"access from a troublemaker, their board will be removed from the GateNet\n"
"AFTER A SINGLE WARNING!!!\n"

